schema_version: https://raw.githubusercontent.com/hubverse-org/hubPredEvalsData/main/inst/schema/v1.0.0/config_schema.json
targets:
- target_id: wk inc covid prop ili
  metrics:
  - ae_median
  - wis
  - interval_coverage_95
  relative_metrics:
  - ae_median
  - wis
  baseline: GZNL-ExponentialSmoothing
  disaggregate_by:
  - target_end_date
  - location
  - horizon
eval_sets:
- eval_set_name: Last 6 weeks
  round_filters:
    min: '2024-11-11'
  task_filters:
    location:
    - "CN"
    horizon:
    - 0
    - -1
    - -2
    - -3
    - -4
    - -5
task_id_text:
  location:
    CN: China
