# Updated: 2026-01-28 13:00 - removed ALL duplicate files (GZNL, XMU, MUST)
schema_version: https://raw.githubusercontent.com/hubverse-org/hubPredEvalsData/main/inst/schema/v1.0.1/config_schema.json
rounds_idx: 0
targets:
- target_id: wk inc covid prop ili
  metrics:
  - ae_median
  - wis
  - interval_coverage_95
  relative_metrics:
  - ae_median
  - wis
  baseline: GZNL-ExponentialSmoothing
  disaggregate_by:
  - target_end_date
  - location
  - horizon
eval_sets:
- eval_set_name: All available weeks
  round_filters:
    min: '2025-09-01'
  task_filters:
    location:
    - "CN"
    horizon:
    - 0
    - -1
    - -2
    - -3
    - -4
    - -5
task_id_text:
  location:
    CN: China
